Added details about cleaned fields on export of plan templates. Added details about processed fields on import of plan templates.
fut-infrastructure/implementation-guide pull request #29
Opened 2024-07-15 13:23 UTC by razvannegrea-sys

Added details about cleaned fields on export of plan templates. Added details about processed fields on import of plan templates.

2024-07-23 10:28 UTC, esn-systematic reviewed
Suggest:

- Updated $get-patient-procedures behavior on input specifying the optional 'extra' parameter. When 'extra' is true, the operation returns a row for extra activities as determined by ServiceRequest.includeAsExtra.
- Updated behavior of custom operation "$apply" on Plan/CarePlan service to transfer the value of includeAsExtra element in PlanDefinition.action to the resulting ServiceRequest.includeAsExtra.

2024-07-24 07:51 UTC, roxanamanea06 commented
Adjusted

> Suggest:
> 
> * Updated $get-patient-procedures behavior on input specifying the optional 'extra' parameter. When 'extra' is true, the operation returns a row for extra activities as determined by ServiceRequest.includeAsExtra.
> * Updated behavior of custom operation "$apply" on Plan/CarePlan service to transfer the value of includeAsExtra element in PlanDefinition.action to the resulting ServiceRequest.includeAsExtra.

2024-07-31 07:40 UTC, esn-systematic requested changes

2024-07-31 12:39 UTC, esn-systematic approved these changes

2024-07-31 12:42 UTC, merged