FUT1-16212 clinicalimpression support invalidation of measurements
fut-infrastructure/implementation-guide pull request #45
Opened 2024-09-03 14:16 UTC by ahpatrifork

2025-01-27 11:31 UTC, esn-systematic requested changes

2025-01-27 11:31 UTC, esn-systematic commented on input/resources/CapabilityStatement-task.json
> +        "documentation": "This operation is used to invalidate or retract an invalidation of a Measurement.\r\n## Input\r\nThe input parameter is a ClinicalImpression resource with the following valu
status COMPLETED is really in lower case (completed).

2025-01-27 11:31 UTC, esn-systematic commented on input/resources/CapabilityStatement-task.json
> +        "documentation": "This operation is used to invalidate or retract an invalidation of a Measurement.\r\n## Input\r\nThe input parameter is a ClinicalImpression resource with the following valu
assossorOrganization shall read assessorOrganization

2025-01-27 11:31 UTC, esn-systematic commented on input/resources/CapabilityStatement-task.json
> +        "documentation": "This operation is used to invalidate or retract an invalidation of a Measurement.\r\n## Input\r\nThe input parameter is a ClinicalImpression resource with the following valu
"The previous ClinicalImpression is determined through the `previous` reference from the input ClinicalImpression. If the `previous` field is not supplied"

Is this still the case? What if ClinicalImpression.previous refers an unrelated ClinicalImpression (not about invalidation/retraction of invalidation)?

2025-01-27 11:31 UTC, esn-systematic commented on input/resources/OperationDefinition-ClinicalImpression-t-set-measurement-validity.json
> +  "description": "This operation is used to invalidate or retract an invalidation of a Measurement.\r\n## Input\r\nThe input parameter is a ClinicalImpression resource with the following values:\r\n-
See comment above about case of COMPLETED which shall be lower case.

See comment above about assossorOrganization.

2025-01-27 12:15 UTC, sysMATGS commented on input/resources/CapabilityStatement-task.json
> +        "documentation": "This operation is used to invalidate or retract an invalidation of a Measurement.\r\n## Input\r\nThe input parameter is a ClinicalImpression resource with the following valu
I changed the following: 
"The previous ClinicalImpression is determined through the `previous` reference from the input ClinicalImpression. If the `previous` field is not supplied, the operation will perform a search for the ClinicalImpression. "
to :
"The operation performs a search for any previous ClinicalImpression in the measurement validity cycle for the measurement, and does not rely on/uypdate the `previous` field on the input ClinicalImpression."

2025-01-28 14:28 UTC, esn-systematic approved these changes

2025-01-28 14:31 UTC, merged